# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mo.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
from motion.core import RobotControl 
import os

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1143, 1078)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

     



        self.pushButtonON1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonON1.setGeometry(QtCore.QRect(10, 30, 88, 27))
        self.pushButtonON1.setObjectName("pushButtonON1")
        self.pushButtonON1.clicked.connect(self.btnON1)

        self.pushButtonPause = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPause.setGeometry(QtCore.QRect(10, 70, 88, 27))
        self.pushButtonPause.setObjectName("pushButtonPause")
        self.pushButtonPause.clicked.connect(self.btnPause)

        self.pushButtonStop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStop.setGeometry(QtCore.QRect(10, 110, 88, 27))
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.pushButtonStop.clicked.connect(self.btnStop)

        self.tableWidgetActualPose = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetActualPose.setGeometry(QtCore.QRect(120, 70, 451, 71))
        self.tableWidgetActualPose.setObjectName("tableWidgetActualPose")
        self.tableWidgetActualPose.setColumnCount(4)
        self.tableWidgetActualPose.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetActualPose.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetActualPose.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetActualPose.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetActualPose.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetActualPose.setHorizontalHeaderItem(3, item)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 30, 141, 19))
        self.label_2.setObjectName("label_2")

        self.pushButtonCart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCart.setGeometry(QtCore.QRect(590, 70, 101, 27))
        self.pushButtonCart.setObjectName("pushButtonCart")
        self.pushButtonCart.clicked.connect(self.btnCart)

        self.pushButtonJoint = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonJoint.setGeometry(QtCore.QRect(590, 110, 101, 27))
        self.pushButtonJoint.setObjectName("pushButtonJoint")
        self.pushButtonJoint.clicked.connect(self.btnJoint)
        

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(810, 30, 121, 20))
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 121, 19))
        self.label_4.setObjectName("label_4")

        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setGeometry(QtCore.QRect(50, 200, 16, 160))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")

        self.verticalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_2.setGeometry(QtCore.QRect(110, 200, 16, 160))
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")

        self.verticalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_3.setGeometry(QtCore.QRect(170, 200, 16, 160))
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")

        self.verticalSlider_4 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_4.setGeometry(QtCore.QRect(230, 200, 16, 160))
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setObjectName("verticalSlider_4")

        self.verticalSlider_5 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_5.setGeometry(QtCore.QRect(290, 200, 16, 160))
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName("verticalSlider_5")

        self.verticalSlider_6 = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider_6.setGeometry(QtCore.QRect(350, 200, 16, 160))
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        
        self.checkBoxTsukl = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxTsukl.setGeometry(QtCore.QRect(450, 260, 92, 25))
        self.checkBoxTsukl.setObjectName("checkBoxTsukl")

        self.pushButtonStopped = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStopped.setGeometry(QtCore.QRect(470, 200, 71, 31))
        self.pushButtonStopped.setObjectName("pushButtonStopped")
        self.pushButtonStopped.clicked.connect(self.btnStopped)

        self.pushButtonWork = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonWork.setGeometry(QtCore.QRect(550, 200, 71, 31))
        self.pushButtonWork.setObjectName("pushButtonWork")
        self.pushButtonWork.clicked.connect(self.btnWork)

        self.pushButtonOff = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOff.setGeometry(QtCore.QRect(630, 200, 71, 31))
        self.pushButtonOff.setObjectName("pushButtonOFf")
        self.pushButtonOff.clicked.connect(self.btnOff)

        self.pushButtonWait = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonWait.setGeometry(QtCore.QRect(710, 200, 71, 31))
        self.pushButtonWait.setObjectName("pushButtonWait")
        self.pushButtonWait.clicked.connect(self.btnWait)

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(820, 70, 291, 181))
        self.widget.setObjectName("widget")

        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(820, 260, 291, 181))
        self.widget_2.setObjectName("widget_2")

        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(820, 460, 291, 181))
        self.widget_3.setObjectName("widget_3")

        self.pushButtonOngr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOngr.setGeometry(QtCore.QRect(440, 330, 88, 27))
        self.pushButtonOngr.setObjectName("pushButtonOngr")
        self.pushButtonOngr.clicked.connect(self.btnOng)
        self.pushButtonOngr.clicked.connect(self.btnOngr)
        
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 300, 66, 19))
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(620, 270, 201, 19))
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 390, 66, 19))
        self.label_7.setObjectName("label_7")

        self.tableWidgetSOST = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetSOST.setGeometry(QtCore.QRect(10, 440, 681, 161))
        self.tableWidgetSOST.setObjectName("tableWidgetSOST")
        self.tableWidgetSOST.setColumnCount(6)
        self.tableWidgetSOST.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSOST.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSOST.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSOST.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSOST.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSOST.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSOST.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSOST.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSOST.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSOST.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSOST.setHorizontalHeaderItem(5, item)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 630, 161, 19))
        self.label_8.setObjectName("label_8")

        self.tableWidgeKoor = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgeKoor.setGeometry(QtCore.QRect(10, 670, 441, 61))
        self.tableWidgeKoor.setObjectName("tableWidgeKoor")
        self.tableWidgeKoor.setColumnCount(4)
        self.tableWidgeKoor.setRowCount(1)
     

        item = QtWidgets.QTableWidgetItem()
        self.tableWidgeKoor.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgeKoor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgeKoor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgeKoor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgeKoor.setHorizontalHeaderItem(3, item)
        self.pushButtonKoorpr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonKoorpr.setGeometry(QtCore.QRect(470, 700, 88, 27))
        self.pushButtonKoorpr.setObjectName("pushButtonKoorpr")
        self.pushButtonKoorpr.clicked.connect(self.auto_move)

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(715, 760, 101, 20))
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(930, 760, 121, 19))
        self.label_10.setObjectName("label_10")

        self.checkBox_2sHTRIH = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2sHTRIH.setGeometry(QtCore.QRect(740, 950, 231, 25))
        self.checkBox_2sHTRIH.setObjectName("checkBox_2sHTRIH")

        self.pushButton_12RED = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12RED.setGeometry(QtCore.QRect(730, 790, 88, 27))
        self.pushButton_12RED.setObjectName("pushButton_12RED")

        self.pushButton_13YELLOW = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13YELLOW.setGeometry(QtCore.QRect(730, 830, 88, 27))
        self.pushButton_13YELLOW.setObjectName("pushButton_13YELLOW")

        self.pushButton_14GREEN = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14GREEN.setGeometry(QtCore.QRect(730, 870, 88, 27))
        self.pushButton_14GREEN.setObjectName("pushButton_14GREEN")

        self.pushButton_15BL = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15BL.setGeometry(QtCore.QRect(730, 910, 88, 27))
        self.pushButton_15BL.setObjectName("pushButton_15BL")

        self.pushButton_16KRUG = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16KRUG.setGeometry(QtCore.QRect(890, 790, 88, 27))
        self.pushButton_16KRUG.setObjectName("pushButton_16KRUG")

        self.pushButton_17KVA = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17KVA.setGeometry(QtCore.QRect(990, 790, 88, 27))
        self.pushButton_17KVA.setObjectName("pushButton_17KVA")

        self.pushButton_18TREG = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18TREG.setGeometry(QtCore.QRect(890, 820, 88, 27))
        self.pushButton_18TREG.setObjectName("pushButton_18TREG")

        self.destinations = {
            "pushButton_12RED": [100, 100, 100],
            "pushButton_14GREEN": [200, 100, 100],
            "pushButton_15BL": [300, 100, 100],
        }



        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 760, 66, 19))
        self.label_11.setObjectName("label_11")

        self.textEditLog = QtWidgets.QTextEdit(self.centralwidget)
        
        self.textEditLog.setGeometry(QtCore.QRect(30, 800, 651, 191))
        self.textEditLog.setObjectName("textEditLog")

        self.pushButtonMovel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMovel.setGeometry(QtCore.QRect(600, 320, 61, 27))
        self.pushButtonMovel.setObjectName("pushButtonMovel")

        self.pushButtonMoveC = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMoveC.setGeometry(QtCore.QRect(670, 320, 61, 27))
        self.pushButtonMoveC.setObjectName("pushButtonMoveC")

        self.pushButtonmOVEJ = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonmOVEJ.setGeometry(QtCore.QRect(740, 320, 61, 27))
        self.pushButtonmOVEJ.setObjectName("pushButtonmOVEJ")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(990, 820, 88, 27))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 860, 88, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1143, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    







    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonON1.setText(_translate("MainWindow", "On"))
        self.pushButtonPause.setText(_translate("MainWindow", "Pause"))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop"))
        item = self.tableWidgetActualPose.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pose"))
        item = self.tableWidgetActualPose.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "x"))
        item = self.tableWidgetActualPose.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "y"))
        item = self.tableWidgetActualPose.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "z"))
        item = self.tableWidgetActualPose.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "gripper"))
        self.label_2.setText(_translate("MainWindow", "Actual tool pose"))
        self.pushButtonCart.setText(_translate("MainWindow", "Manual Cart"))
        self.pushButtonJoint.setText(_translate("MainWindow", "Manual Joint"))
        self.label_3.setText(_translate("MainWindow", "Видео с камер"))
        self.label_4.setText(_translate("MainWindow", "For  Manual"))
        self.checkBoxTsukl.setText(_translate("MainWindow", "Цикл"))
        self.pushButtonStopped.setText(_translate("MainWindow", "Stopped"))
        self.pushButtonWork.setText(_translate("MainWindow", "Work"))
        self.pushButtonOff.setText(_translate("MainWindow", "Off"))
        self.pushButtonWait.setText(_translate("MainWindow", "Wait"))
        self.pushButtonOngr.setText(_translate("MainWindow", "On"))
        self.label_5.setText(_translate("MainWindow", "Gripper"))
        self.label_6.setText(_translate("MainWindow", "Стиль движения"))
        self.label_7.setText(_translate("MainWindow", "Состояние моторов"))
        item = self.tableWidgetSOST.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "тики"))
        item = self.tableWidgetSOST.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "радианы"))
        item = self.tableWidgetSOST.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "градусы"))
        item = self.tableWidgetSOST.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "тем-ра"))
        item = self.tableWidgetSOST.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetSOST.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetSOST.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetSOST.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidgetSOST.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidgetSOST.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        self.label_8.setText(_translate("MainWindow", "Задать координаты"))
        item = self.tableWidgeKoor.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Pose"))
        item = self.tableWidgeKoor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "x"))
        item = self.tableWidgeKoor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "y"))
        item = self.tableWidgeKoor.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "z"))
        item = self.tableWidgeKoor.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "gripper"))
        self.pushButtonKoorpr.setText(_translate("MainWindow", "Применить"))
        self.label_9.setText(_translate("MainWindow", "Цвета объекта"))
        self.label_10.setText(_translate("MainWindow", "Форма объекта"))
        self.checkBox_2sHTRIH.setText(_translate("MainWindow", "Считывание штрих-кодов"))
        self.pushButton_12RED.setText(_translate("MainWindow", "Красный"))
        self.pushButton_13YELLOW.setText(_translate("MainWindow", "Жёлтый"))
        self.pushButton_14GREEN.setText(_translate("MainWindow", "Зеленый"))
        self.pushButton_15BL.setText(_translate("MainWindow", "Синий"))
        self.pushButton_16KRUG.setText(_translate("MainWindow", "1"))
        self.pushButton_17KVA.setText(_translate("MainWindow", "2"))
        self.pushButton_18TREG.setText(_translate("MainWindow", "3"))
        self.label_11.setText(_translate("MainWindow", "Логи"))
        self.pushButtonMovel.setText(_translate("MainWindow", "Move l"))
        self.pushButtonMoveC.setText(_translate("MainWindow", "Move C"))
        self.pushButtonmOVEJ.setText(_translate("MainWindow", "Move J"))
        self.pushButton.setText(_translate("MainWindow", "4"))
        self.pushButton_2.setText(_translate("MainWindow", "5"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))






    def btnON1(self):
            loga = "Робот включен"
            self.textEditLog.append(loga)
            with open("log.txt", "a") as f:
                f.write(loga + "\n")

       

    def btnStop(self):
        lodc = "Робот остановлен"
        self.textEditLog.append(lodc)
        with open("log.txt", "a") as f:
            f.write(lodc + "\n")

        
    def btnOngr(self):  
        lodz = "Гриппер  включен"
        self.textEditLog.append(lodz)
        with open("log.txt", "a") as f:
            f.write(lodz + "\n")


    def btnPause(self):
        c = 0
        c = c + 1
        if c % 2 != 0:
            logb = "Робот поставлен на паузу"
            self.textEditLog.append(logb)
            with open("log.txt", "a") as f:
                f.write(logb + "\n")
           
        else:
            lodb2 = "Робот снят с паузы работу"
            self.textEditLog.append(lodb2)

    def btnCart(self):
        logd = "Робот переведен в ручной режим"
        self.textEditLog.append(logd)
        with open("log.txt", "a") as f:
            f.write(logd + "\n")
       

    def btnStopped(self):
        logi =  "Работа робота остановлена"
        self.textEditLog.append(logi)
        with open("log.txt", "a") as f:
            f.write(logi + "\n")


    def btnWork(self):
        logf =  "Робот выполняет заданные действия" 
        self.textEditLog.append(logf)
        with open("log.txt", "a") as f:
            f.write(logf + "\n")

    def btnWait(self):
        logn = "Робот в режиме ожидания"
        self.textEditLog.append(logn)
        with open("log.txt", "a") as f:
            f.write(logn + "\n")


    def btnOff(self):
        logg = "Работа робота прекращена"
        self.textEditLog.append(logg)
        with open("log.txt", "a") as f:
            f.write(logg + "\n")


    def btnOng(self):
        logk = "Включен гриппер"
        self.textEditLog.append(logk)
        with open("log.txt", "a") as f:
            f.write(logk + "\n")

    def btnJoint(self):
        logd = "Робот переведен в авто режим"
        self.textEditLog.append(logd)
        with open("log.txt", "a") as f:
            f.write(logd + "\n")

    def auto_move(self): 
        try:
            x = float(self.tableWidgeKoor.item(0, 0).text())
            y = float(self.tableWidgeKoor.item(0, 1).text())
            z = float(self.tableWidgeKoor.item(0, 2).text())
            gripper = self.tableWidgeKoor.item(0, 3).text().lower() == "true"

            if not (0 <= x <= 950 and 0 <= y <= 950 and 0 <= z <= 950):
                self.log("Ошибка: координаты вне рабочей зоны")
                return

            self.set_status("Work")
            self.robot.moveL([x, y, z])
            if gripper:
                self.robot.controlGripper(True)
            self.robot.moveL([x+50, y+50, z]) 
            if gripper:
                self.robot.controlGripper(False)

            self.update_pose_table([x+50, y+50, z, "Open" if not gripper else "Closed"])
            self.update_motor_table()
            self.log(f"Перемещение в ({x}, {y}, {z}) завершено.")

        except Exception as e:
            self.log(f"Ошибка: {e}")
            self.set_status("Stopped")

    def update_pose_table(self, coords):
        for i, val in enumerate(coords):
            self.tableWidgetActualPose.setItem(0, i, QTableWidgetItem(str(val)))

    def update_motor_table(self):
        states = self.robot.getMotorStates()  
        for row in range(min(4, len(states))):
            for col in range(min(6, len(states[row]))):
                self.tableWidgetSOST.setItem(row, col, QTableWidgetItem(str(states[row][col]))) 
    def log(self, text):
        self.textEditLog.append(text)
        with open("log.txt", "a") as f:
            f.write(text + "\n")
        

    def set_status(self, status):
        colors = {"Stopped": "red", "Work": "green", "Off": "red", "Wait": "yellow"}
        for s in colors:
            getattr(self, f"pushButton{s}").setStyleSheet(f"background-color: none")
        getattr(self, f"pushButton{status}").setStyleSheet(f"background-color: {colors[status]}")
    





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
